name: Daily HubSpot-Dialpad Sync

on:
  schedule:
    # Run at 2 AM AEST (UTC+10) every day
    - cron: '0 16 * * *'
  workflow_dispatch:  # allows manual triggering from GitHub UI

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Sync
        run: python hubspot_sync.py
